Add support for direct to parquet files
mozilla/parquet2hive pull request #28
Opened 2017-02-23 22:03 UTC by robotblake

This is super gross and doesn't have tests (beyond my own local testing) but appears to work.  I ended up just scrapping a whole bunch of work and made the new code path only handle direct-to-parquet files so this could get pushed out.

2017-02-23 22:34 UTC, fbertsch commented
Can you describe what you tested this on? Just so I can get an idea of what's been covered.

2017-02-24 14:25 UTC, fbertsch requested changes

2017-02-24 14:25 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +def parquet2sql_fields(schema, children):
The docs say that `schema` is a list of `SchemaElements`, which actually represents the tree but in depth-first traversal. Isn't this function assuming it's breadth first traversal? I.e. for
```
   p
  / \
 c1 c2
 /
c3
```
it assumes `[p, c1, c2, c3]`, but depth-first traversal would be  `[p, c1, c3, c2]`

2017-02-24 14:25 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +    if data_type[0] == "array":
I see this repeated in 3 functions. Please pull it out to a separate function

2017-02-24 14:25 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +    key_type = data_type[0][1][1][1][0][1][0]
Can you document the reason there is this path to the key/value?

2017-02-24 14:26 UTC, fbertsch commented
@robotblake we should make it a priority to include tests for this. Trink would probably be happy to help make a direct-to-parquet output with most/all data types that we could test on.

2017-02-28 18:28 UTC, fbertsch commented on tests/parquet2hive_test.py
> +
No tree for the complex schema? ;)

2017-02-28 18:28 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +    if elem[0] == 'repeated' and root:
A special case for root-level repeated elements? That seems... odd.

2017-02-28 18:29 UTC, robotblake commented on parquet2hive_modules/parquet2hivelib.py
> +    if elem[0] == 'repeated' and root:
Yeah, that does look wrong, let me take a look.

2017-03-03 20:24 UTC, robotblake commented
I added a pretty in-depth test case and a ton of tests, I also tested that the SQL generated by the old methods match the SQL generated by the new method against all of the datasets in the telemetry-parquet bucket.

2017-03-03 21:58 UTC, fbertsch requested changes

2017-03-03 21:58 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +            retval.append((repetition, elem_type, elem.name, converted, subs))
Why not have this instead append a dict, and label each element (e.g. {"repetition": repetition, "type": elem_type, etc.}). Would make this, and the rest of the code, more readable.

2017-03-03 21:58 UTC, fbertsch commented on parquet2hive_modules/parquet2hivelib.py
> +    if elem[1] == 'group' and elem[3] == 'list' and len(elem[4]) == 1:
Can you put some comments here describing these structures and control flow?

2017-03-03 21:58 UTC, fbertsch commented on tests/parquet2hive_test.py
> +COMPLEX_SQL = "drop table if exists complex_table; " \
I think I would prefer these moved to a separate .sql file

2017-03-07 02:50 UTC, fbertsch commented
@robotblake have you had a chance to test this on the new direct-to-parquet versioned datasets?

2017-03-07 23:12 UTC, fbertsch approved these changes

2017-03-07 23:12 UTC, merged